isotopeData = [{
        "name": "Neutron",
        "color": "#000000",
        "textColor": "#FFFFFF",
        "symbol": "n",
        "w": 1,
        "isotopes": [
            "s",
            "s"
        ]
    },
    {
        "name": "Hydrogen",
        "color": "#FFFFFF",
        "symbol": "H",
        "w": 1,
        "isotopes": [
            "s",
            "s",
            "b-",
            "n",
            "2n",
            "n",
            "2n"
        ]
    },
    {
        "name": "Helium",
        "color": "#D9FFFF",
        "symbol": "He",
        "w": 2,
        "isotopes": [
            "b+",
            "s",
            "s",
            "n",
            "b-",
            "n",
            "b-",
            "n",
            "2n"
        ]
    },
    {
        "name": "Lithium",
        "color": "#CC80FF",
        "symbol": "Li",
        "w": 3,
        "isotopes": [
            "p",
            "p",
            "p",
            "s",
            "s",
            "b-",
            "b-",
            "n",
            "b-",
            "n",
            "2n"
        ]
    },
    {
        "name": "Beryllium",
        "color": "#C2FF00",
        "symbol": "Be",
        "w": 5,
        "isotopes": [
            "p",
            "2p",
            "e-c",
            "a",
            "s",
            "b-",
            "b-",
            "b-",
            "n",
            "b-",
            "n",
            "2n"
        ]
    },
    {
        "name": "Boron",
        "color": "#FFB5B5",
        "symbol": "B",
        "w": 6,
        "isotopes": [
            "2p",
            "p",
            "b+",
            "p",
            "s",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "n",
            "b-",
            "n",
            "b-",
            "n",
            "n"
        ]
    },
    {
        "name": "Carbon",
        "color": "#909090",
        "symbol": "C",
        "w": 8,
        "isotopes": [
            "2p",
            "b+",
            "b+",
            "b+",
            "s",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "n",
            "b-",
            "n",
            "b-",
            "n",
            "n",
        ]
    },
    {
        "name": "Nitrogen",
        "color": "#0C0CFF",
        "textColor": "#FFFFFF",
        "symbol": "N",
        "w": 10,
        "isotopes": [
            "p",
            "p",
            "b+",
            "b+",
            "s",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "n",
            "n"
        ]
    },
    {
        "name": "Oxygen",
        "color": "#FF0C0C",
        "textColor": "#FFFFFF",
        "symbol": "O",
        "w": 12,
        "isotopes": [
            "2p",
            "b+",
            "b+",
            "b+",
            "s",
            "s",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "n",
            "b-",
            "n"
        ]
    },
    {
        "name": "Fluorine",
        "color": "#90E050",
        "symbol": "F",
        "w": 14,
        "isotopes": [
            "p",
            "p",
            "p",
            "b+",
            "b+",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "n",
            "b-",
            "n",
            "b-"
        ]
    },
    {
        "name": "Neon",
        "color": "#B3E3F5",
        "symbol": "Ne",
        "w": 15,
        "isotopes": [
            "2p",
            "2p",
            "b+",
            "b+",
            "b+",
            "s",
            "s",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "n",
            "b-",
            "n",
            "b-"
        ]
    },
    {
        "name": "Sodium",
        "color": "#AB5CF3",
        "symbol": "Na",
        "w": 17,
        "isotopes": [
            "p",
            "p",
            "p",
            "b+",
            "b+",
            "b+",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "n",
            "b-",
        ]
    },
    {
        "name": "Magnesium",
        "color": "#8AFF00",
        "symbol": "Mg",
        "w": 19,
        "isotopes": [
            "2p",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "s",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "n",
            "b-"
        ]
    },
    {
        "name": "Aluminium",
        "color": "#BFA6A6",
        "symbol": "Al",
        "w": 21,
        "isotopes": [
            "p",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Silicon",
        "color": "#809999",
        "symbol": "Si",
        "w": 22,
        "isotopes": [
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "s",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Phosphorus",
        "color": "#FF8000",
        "symbol": "P",
        "w": 24,
        "isotopes": [
            "p",
            "p",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Sulfur",
        "color": "#FFFF30",
        "symbol": "S",
        "w": 26,
        "isotopes": [
            "2p",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "s",
            "s",
            "b-",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "n",
        ]
    },
    {
        "name": "Chlorine",
        "color": "#1FF01F",
        "symbol": "Cl",
        "w": 28,
        "isotopes": [
            "p",
            "p",
            "p",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "b-",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Argon",
        "color": "#80D1E3",
        "symbol": "Ar",
        "w": 30,
        "isotopes": [
            "2p",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "e-c",
            "s",
            "b-",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Potassium",
        "color": "#8F40D4",
        "textColor": "#FFFFFF",
        "symbol": "K",
        "w": 32,
        "isotopes": [
            "p",
            "p",
            "p",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "s",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Calcium",
        "color": "#3DFF00",
        "symbol": "Ca",
        "w": 34,
        "isotopes": [
            "2p",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "e-c",
            "s",
            "s",
            "s",
            "b-",
            "s",
            "b-",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Scandium",
        "color": "#E6E6E6",
        "symbol": "Sc",
        "w": 36,
        "isotopes": [
            "p",
            "p",
            "p",
            "p",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Titanium",
        "color": "#BFC2C7",
        "symbol": "Ti",
        "w": 38,
        "isotopes": [
            "2p",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "e-c",
            "b+",
            "s",
            "s",
            "s",
            "s",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Vanadium",
        "color": "#E6E6E6",
        "symbol": "V",
        "w": 40,
        "isotopes": [
            "p",
            "p",
            "p",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "e-c",
            "s",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Chromium",
        "color": "#BFC2C7",
        "symbol": "Cr",
        "w": 42,
        "isotopes": [
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "e-c",
            "s",
            "s",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Manganese",
        "color": "#9C7AC7",
        "symbol": "Mn",
        "w": 44,
        "isotopes": [
            "p",
            "p",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "e-c",
            "e-c",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Iron",
        "color": "#E06633",
        "symbol": "Fe",
        "w": 45,
        "isotopes": [
            "2p",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "e-c",
            "s",
            "s",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Cobalt",
        "color": "#F090A0",
        "symbol": "Co",
        "w": 47,
        "isotopes": [
            "p",
            "p",
            "p",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "e-c",
            "b+",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
    {
        "name": "Nickel",
        "color": "#50D050",
        "symbol": "Ni",
        "w": 48,
        "isotopes": [
            "2p",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "b+",
            "s",
            "b+",
            "s",
            "s",
            "s",
            "b-",
            "s",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
            "b-",
        ]
    },
];